### PR TITLE
prevent sortable field on forms

### PR DESCRIPTION
**Pull request by dillingham**

### CODE REVIEW

**Comment by dillingham** [comment]
@Naxon can you merge this please?

**Comment by jBOKA** [comment]
@dillingham Is this PR not going to happen? Seemed legit to me.

**Comment by dillingham** [comment]
@jBOKA $this->exceptOnForms(); needed to be explicitly

```
    public $showOnCreation = false;
    
    public $showOnUpdate = false;
```
I added it to my fork here, which is working.

https://github.com/dillingham/nova-field-sortable

**Comment by jBOKA** [comment]
@dillingham thx for your help. I opened another Issue that i found to be important, didn't know this repo is kind of dead. Before I go any further with this field:
Do you have any plans to put work into this? My issue isn't really a quickfix I'm afraid.

**Pull request closed without merging**
